kind: pipeline
name: triton

steps:
  - name: Compile
    image: ubuntu:latest
    environment:
            TOKEN:
                    from_secret: token
            CID:
                    from_secret: cid
            MEGAP:
                    from_secret: megap
            MEGAU:
                    from_secret: megau
    commands:
      - chmod +x compiler.sh
      - bash compiler.sh
      
