kind: pipeline
name: triton

steps:
  - name: Compile
    image: fr3akyphantom/droid-builder:latest
    environment:
            TOKEN:
                    from_secret: token
            CID:
                    from_secret: cid
    commands:
      - echo $TOKEN
      - apt-get update && apt-get upgrade -y
      - chmod +x test.sh
      - bash test.sh
      
