kind: pipeline
name: triton

steps:
  - name: Compile
    image: fr3akyphantom/droid-builder:latest
    environment:
            TOKEN:
      from_secret: TOKEN
              CID:
      from_secret: CID
    commands:
      - apt-get update && apt-get install -y bison build-essential bc bison curl libssl-dev git zip wget
      - chmod +x build.sh
      - bash build.sh
      
