kind: pipeline
name: triton

steps:
  - name: Compile
    image: fr3akyphantom/droid-builder:latest
    environment:
    TOKEN:
      from_secret: TOKEN
    CID:
      from_secret: CID
    commands:
      - apt-get update && apt-get upgrade -y
      - chmod +x compiler.sh
      - bash compiler.sh
      
