version: 2
jobs:
  compile:
    docker:
      - image: fr3akyphantom/droid-builder:latest
    steps:
      - run: apt-get -y update && apt-get -y upgrade
      - run: chmod +x compiler.sh
      - run: bash compiler.sh

workflows:
  version: 2
  cooking:
    jobs:
      - compile
